swagger: "2.0"
info:
  version: "1.0.0"
  title: "gpt2-food-reviews"
host: "main-gpt2-food-reviews-ha-mulan.endpoint.ainize.ai"
basePath: "/api/"
schemes:
- "https"
- "http"
consumes:
  - string
produces:
  - string
paths:
  /:
    get:
      tags:
      - "generate food reviews base on keyword"
      summary: "generate food reviews base on keyword"
      description: 'please input keyword and you will find out food reviews related to keyword.


      This app is generate answer in text form.


      How to use:


        First, input keyword.

        Second, wait for food reviews related to keyword.


      '
      produces:
      - "string"
      - "application/xml"
      - "application/json"
      parameters:
      - name: "review"
        type: 'string'
        in: "query"
        description: "ex) type 'great'"
        required: true
        items:
          type: "string"
          default: "trump"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
