swagger: "2.0"
info:
  version: "1.0.0"
  title: "gpt2-recipe-maker"
host: "master-gpt2-recipe-maker-ha-mulan.endpoint.ainize.ai"
basePath: "/api/"
schemes:
- "https"
- "http"
consumes:
  - string
produces:
  - string
paths:
  /:
    get:
      tags:
      - "make recipe related to cuisine"
      summary: "create recipe"
      description: "please input name of cuisine"
      produces:
      - "string"
      - "application/xml"
      - "application/json"
      parameters:
      - name: "food"
        type: 'string'
        in: "query"
        description: "name of cuisine"
        required: true
        items:
          type: "string"
          default: "trump"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"